=== FH-Thomas-Herzog/xml/20150226_hands_on_1/b2_termin.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % DATE_TIME "(DATE, TIME?)">
<!ENTITY % PARTICIPANT SYSTEM "b3_teilnehmerListe.ent">
<!ELEMENT APPOINTMENT (STARTDATE?, ENDDATE?, DURATION, APPOINTMENT_DESCRIPTION, APPOINTMENT_NOTIFICATIONS, PARTICIPANT_LIST)>
<!ELEMENT STARTDATE %DATE_TIME;>
<!ELEMENT ENDDATE %DATE_TIME;>
<!ELEMENT DATE (DAY, MONTH, YEAR)>
<!ELEMENT TIME (HOUR, MINUTE)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT MONTH (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT HOUR (#PCDATA)>
<!ELEMENT MINUTE (#PCDATA)>
<!ELEMENT DURATION (#PCDATA)>
<!ELEMENT APPOINTMENT_DESCRIPTION (DESCRIPTION_TITLE, DESCRIPTION, APPOINTMENT_TYPE, APPOINTMENT_LOCATION?, APPOINTMENT_LINK?)>
<!ELEMENT DESCRIPTION_TITLE (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT APPOINTMENT_TYPE (#PCDATA)>
<!ELEMENT APPOINTMENT_LOCATION (#PCDATA)>
<!ELEMENT APPOINTMENT_LINK (#PCDATA)>
<!ELEMENT APPOINTMENT_NOTIFICATIONS (NOTIFICATION*)>
<!ELEMENT NOTIFICATION (#PCDATA)>
<!ELEMENT PARTICIPANT_LIST (PARTICIPANT*)>
%PARTICIPANT;
<!ATTLIST APPOINTMENT
	id ID #REQUIRED
	name CDATA #REQUIRED
	creator CDATA #REQUIRED
	movable (true | false) #REQUIRED
	serialized (true | false) #REQUIRED
>
<!ATTLIST DURATION
	type (hour) "hour"
>
<!ATTLIST NOTIFICATION
	type (Beep | EMail | Fax) #REQUIRED
	period (day | minute) #REQUIRED
>

=== FH-Thomas-Herzog/xml/20150226_hands_on_1/b2_termin.xml
<!DOCTYPE APPOINTMENT SYSTEM "b2_termin.dtd">
<APPOINTMENT id="A1" name="appointment_1" creator="P1" movable="true" serialized="false">
	<STARTDATE>
		<DATE>
			<DAY>26</DAY>
			<MONTH>4</MONTH>
			<YEAR>1999</YEAR>
		</DATE>
		<TIME>
			<HOUR>13</HOUR>
			<MINUTE>00</MINUTE>
		</TIME>
	</STARTDATE>
	<ENDDATE>
		<DATE>
			<DAY>26</DAY>
			<MONTH>4</MONTH>
			<YEAR>1999</YEAR>
		</DATE>
		<TIME>
			<HOUR>14</HOUR>
			<MINUTE>30</MINUTE>
		</TIME>
	</ENDDATE>
	<DURATION>
		1.50
	</DURATION>
	<APPOINTMENT_DESCRIPTION>
		<DESCRIPTION_TITLE> 
			Vorlesung Softwareentwicklung 2
		</DESCRIPTION_TITLE>
		<DESCRIPTION>
			Design Patterns
		</DESCRIPTION>
		<APPOINTMENT_TYPE>
			Lehre
		</APPOINTMENT_TYPE>
		<APPOINTMENT_LOCATION>
			HS 23
		</APPOINTMENT_LOCATION>
		<APPOINTMENT_LINK>
			http://www.google.at
		</APPOINTMENT_LINK>
	</APPOINTMENT_DESCRIPTION>
	<APPOINTMENT_NOTIFICATIONS>
		<NOTIFICATION type="EMail" period="day">
				1
			</NOTIFICATION>
		<NOTIFICATION type="Beep" period="day">
				1
			</NOTIFICATION>
	</APPOINTMENT_NOTIFICATIONS>
	<PARTICIPANT_LIST>
		<PARTICIPANT id="P1" name="Thomas Herzog" email="thomas.herzog@students.fh-hagenberg.at"/>
		<PARTICIPANT id="P2" name="Thomas Herzog" email="thomas.herzog@students.fh-hagenberg.at"/>
		<PARTICIPANT id="P3" name="Thomas Herzog" email="thomas.herzog@students.fh-hagenberg.at"/>
	</PARTICIPANT_LIST>
</APPOINTMENT>
